/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cWtKnSrZ4qsbr8L4UPdwwh

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsunb08U024E5N } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Unb08U024e5N/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsunb08U024E5N
});
